---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]


  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "Red Hat"


  - name: install httpd and hph packages
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Red Hat"



